# Generated by Django 5.2.9 on 2026-01-05 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mileage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mileage", models.PositiveIntegerField(verbose_name="Пробег")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год регистрации")),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.car",
                        verbose_name="Авто",
                    ),
                ),
                (
                    "moto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.moto",
                        verbose_name="Мотоцикл",
                    ),
                ),
            ],
            options={
                "verbose_name": "пробег",
                "verbose_name_plural": "пробег",
                "ordering": ["-year"],
            },
        ),
    ]
