# Generated by Django 5.2.9 on 2026-01-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_mileage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mileage",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mileage",
                to="vehicle.car",
                verbose_name="Авто",
            ),
        ),
        migrations.AlterField(
            model_name="mileage",
            name="moto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mileage",
                to="vehicle.moto",
                verbose_name="Мотоцикл",
            ),
        ),
    ]
